version: '1.0'
services:
  postgres:
    image: postgres:13
    container_name: chat-app-postgresDB
    restart: always
    ports:
      - 7777:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: chat-app-db
